# Generated by Django 4.0.2 on 2022-04-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='confirm_password',
            field=models.CharField(max_length=500),
        ),
    ]
